### ISSUE TITLE
It didn't start :(

### ISSUE THREAD

**Issue by alexdavies74** [aarongut/cmdasana#1]
Hey Aaron,
I tried running a fresh clone, but it crashed:

Alex-Daviess-MacBook-Pro:sandbox asana$ git clone https://github.com/aarongut/cmdasana.git
Cloning into 'cmdasana'...
remote: Counting objects: 236, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 236 (delta 7), reused 0 (delta 0), pack-reused 220
Receiving objects: 100% (236/236), 228.65 KiB | 148.00 KiB/s, done.
Resolving deltas: 100% (116/116), done.
Checking connectivity... done.
Alex-Daviess-MacBook-Pro:sandbox asana$ cd cmdasana/
Alex-Daviess-MacBook-Pro:cmdasana asana$ make
git submodule init
Submodule 'python-asana' (git@github.com:Asana/python-asana.git) registered for path 'python-asana'
git submodule update
Cloning into 'python-asana'...
remote: Counting objects: 699, done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 699 (delta 29), reused 0 (delta 0), pack-reused 637
Receiving objects: 100% (699/699), 142.03 KiB | 0 bytes/s, done.
Resolving deltas: 100% (440/440), done.
Checking connectivity... done.
Submodule path 'python-asana': checked out '66c31afc60bd0bc1c6e727ce580539ca9d0e938d'
Alex-Daviess-MacBook-Pro:cmdasana asana$ ./cmdasana.py 
Traceback (most recent call last):
  File "./cmdasana.py", line 9, in <module>
    import asana
  File "/Users/asana/sandbox/cmdasana/asana/**init**.py", line 1, in <module>
    from .client import Client
  File "/Users/asana/sandbox/cmdasana/asana/client.py", line 1, in <module>
    from . import session
  File "/Users/asana/sandbox/cmdasana/asana/session.py", line 2, in <module>
    import requests_oauthlib
  File "/Library/Python/2.7/site-packages/requests_oauthlib/**init**.py", line 1, in <module>
    from .oauth1_auth import OAuth1
  File "/Library/Python/2.7/site-packages/requests_oauthlib/oauth1_auth.py", line 7, in <module>
    from oauthlib.oauth1 import Client, SIGNATURE_HMAC, SIGNATURE_TYPE_AUTH_HEADER
ImportError: cannot import name SIGNATURE_HMAC

**Comment by aarongut** [comment]
I've never run into this problem. Sorry this isn't working for you :(
It looks like upgrading oauthlib might fix the problem.  `sudo pip install --upgrade oauthlib`

**Comment by alexdavies74** [comment]
It got a little further!

Alex-Daviess-MacBook-Pro:cmdasana asana$ ./cmdasana.py 
Traceback (most recent call last):
  File "./cmdasana.py", line 9, in <module>
    import asana
  File "/Users/asana/sandbox/cmdasana/cmdasana/asana/**init**.py", line 1, in <module>
    from .client import Client
  File "/Users/asana/sandbox/cmdasana/cmdasana/asana/client.py", line 1, in <module>
    from . import session
  File "/Users/asana/sandbox/cmdasana/cmdasana/asana/session.py", line 2, in <module>
    import requests_oauthlib
  File "/Library/Python/2.7/site-packages/requests_oauthlib/**init**.py", line 1, in <module>
    from .oauth1_auth import OAuth1
  File "/Library/Python/2.7/site-packages/requests_oauthlib/oauth1_auth.py", line 10, in <module>
    from requests.utils import to_native_string
ImportError: cannot import name to_native_string
